name: Build CS 1.6 Client for PC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y build-essential libglib2.0-dev libx11-dev libgl-dev  # İhtiyaç duyduğunuz kütüphaneler
        sudo apt-get install -y g++ gcc make  # CMake ve derleyici araçları

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cs-client-build
        path: ./build
