name: Build CS 1.6 Client for PC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y build-essential libglib2.0-dev libx11-dev libgl-dev
        sudo apt-get install -y g++ gcc make

    - name: Clean up and build project
      run: |
        cd ./  # CMakeLists.txt dosyasının olduğu dizine geçiş yapıyoruz
        cmake ..  # CMakeLists.txt dosyasının olduğu dizine işaret ediyor
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cs-client-build
        path: ./build
